{{- if gt (int .Values.workersNumber) 0 }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ include "hcloudmachinetemplate.worker.name" . }}
spec:
  template:
    spec:
      imageName: {{ .Values.worker.image }}
      type: {{ .Values.worker.type }}
      {{- if .Values.worker.placementGroupName }}
      placementGroupName: {{ .Values.worker.placementGroupName }}
      {{- end }}
      {{- with .Values.worker.dataDisks }}
      dataDisks:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.additionalSecurityGroups }}
      additionalSecurityGroups:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}