apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ include "hcloudmachinetemplate.controlplane.name" . }}
spec:
  template:
    spec:
      imageName: {{ .Values.controlPlane.image }}
      type: {{ .Values.controlPlane.type }}
      {{- if .Values.controlPlane.placementGroupName }}
      placementGroupName: {{ .Values.controlPlane.placementGroupName }}
      {{- end }}
      {{- with .Values.controlPlane.dataDisks }}
      dataDisks:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlPlane.additionalSecurityGroups }}
      additionalSecurityGroups:
        {{- toYaml . | nindent 8 }}
      {{- end }}